// Code generated by "stringer -type=DimensionType"; DO NOT EDIT.

package jdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DimensionUnknown-0]
}

const _DimensionType_name = "DimensionUnknown"

var _DimensionType_index = [...]uint8{0, 16}

func (i DimensionType) String() string {
	if i >= DimensionType(len(_DimensionType_index)-1) {
		return "DimensionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DimensionType_name[_DimensionType_index[i]:_DimensionType_index[i+1]]
}
