name: CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.0'

    - name: Test
      run: |
        chmod 0400 testdata/ro.db
        go test -covermode=count -coverprofile=coverage.out -v -count 100 -failfast ./...


    - name: gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
        golangci-lint run --skip-files='.*_test.go'

    - name: Archive stuff
      uses: actions/upload-artifact@v4.0.0
      with:
        name: build-artefacts
        path: |
          coverage.out

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Generate SBOM
      uses: CycloneDX/gh-gomod-generate-sbom@v2
      with:
        version: v1
        args: mod -licenses -json -output bom.json

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bom.json
          coverage.out
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
